# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExampleService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ExampleService.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x45xampleService.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"b\n\x14SimpleExampleMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07message\x18\x03 \x01(\t\"c\n\x15SimpleExampleResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07message\x18\x03 \x01(\t2\xc4\x02\n\x0e\x45xampleService\x12J\n\x17MessageToMessageExample\x12\x15.SimpleExampleMessage\x1a\x16.SimpleExampleResponse\"\x00\x12K\n\x16MessageToStreamExample\x12\x15.SimpleExampleMessage\x1a\x16.SimpleExampleResponse\"\x00\x30\x01\x12K\n\x16StreamToMessageExample\x12\x15.SimpleExampleMessage\x1a\x16.SimpleExampleResponse\"\x00(\x01\x12L\n\x15StreamToStreamExample\x12\x15.SimpleExampleMessage\x1a\x16.SimpleExampleResponse\"\x00(\x01\x30\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_SIMPLEEXAMPLEMESSAGE = _descriptor.Descriptor(
  name='SimpleExampleMessage',
  full_name='SimpleExampleMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='SimpleExampleMessage.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='SimpleExampleMessage.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='SimpleExampleMessage.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=155,
)


_SIMPLEEXAMPLERESPONSE = _descriptor.Descriptor(
  name='SimpleExampleResponse',
  full_name='SimpleExampleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='SimpleExampleResponse.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='SimpleExampleResponse.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='SimpleExampleResponse.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=256,
)

_SIMPLEEXAMPLEMESSAGE.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SIMPLEEXAMPLERESPONSE.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['SimpleExampleMessage'] = _SIMPLEEXAMPLEMESSAGE
DESCRIPTOR.message_types_by_name['SimpleExampleResponse'] = _SIMPLEEXAMPLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimpleExampleMessage = _reflection.GeneratedProtocolMessageType('SimpleExampleMessage', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLEEXAMPLEMESSAGE,
  '__module__' : 'ExampleService_pb2'
  # @@protoc_insertion_point(class_scope:SimpleExampleMessage)
  })
_sym_db.RegisterMessage(SimpleExampleMessage)

SimpleExampleResponse = _reflection.GeneratedProtocolMessageType('SimpleExampleResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLEEXAMPLERESPONSE,
  '__module__' : 'ExampleService_pb2'
  # @@protoc_insertion_point(class_scope:SimpleExampleResponse)
  })
_sym_db.RegisterMessage(SimpleExampleResponse)



_EXAMPLESERVICE = _descriptor.ServiceDescriptor(
  name='ExampleService',
  full_name='ExampleService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=259,
  serialized_end=583,
  methods=[
  _descriptor.MethodDescriptor(
    name='MessageToMessageExample',
    full_name='ExampleService.MessageToMessageExample',
    index=0,
    containing_service=None,
    input_type=_SIMPLEEXAMPLEMESSAGE,
    output_type=_SIMPLEEXAMPLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='MessageToStreamExample',
    full_name='ExampleService.MessageToStreamExample',
    index=1,
    containing_service=None,
    input_type=_SIMPLEEXAMPLEMESSAGE,
    output_type=_SIMPLEEXAMPLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StreamToMessageExample',
    full_name='ExampleService.StreamToMessageExample',
    index=2,
    containing_service=None,
    input_type=_SIMPLEEXAMPLEMESSAGE,
    output_type=_SIMPLEEXAMPLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StreamToStreamExample',
    full_name='ExampleService.StreamToStreamExample',
    index=3,
    containing_service=None,
    input_type=_SIMPLEEXAMPLEMESSAGE,
    output_type=_SIMPLEEXAMPLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXAMPLESERVICE)

DESCRIPTOR.services_by_name['ExampleService'] = _EXAMPLESERVICE

# @@protoc_insertion_point(module_scope)
